##BitPay Sample Appcelerator App

This app requires the following

1. One of the BitPay libraries are setup
2. An API Key is set on the server to link the app to the API Endpoint
3. The response is sent back in a JSON format with the following fields

```
status = success <or your own custom error response>
msg = custom message
invoice_url = the url generated by the library so the module can load the webview
invoice_id  = the transaction id
```

The module **must** used the following paramter names (you can add your custom ones as needed)

```
var item = {
        'sku': '<sku>',
        'description': <product description>,
        'price': parseFloat(<price of item>),
        'buyer_email': '<buyers email>'
    }
```


